#!/usr/bin/python
from bs4 import BeautifulSoup
import requests
characters = open("temp.txt","r")
twitter_data = open("twitter_data.txt","w+")
url = "https://twitter.com/search?f=users&q="
account_url="https://twitter.com"
for char in characters:
	print "Getting data for ",char
	soup = BeautifulSoup(requests.get(url+char.replace(" ","%20")).content,"html.parser")
	results = soup.find_all("div",{"class":"ProfileCard  js-actionable-user"})
	followers = 0
	handle = ""
	for res in results:
		handle = res.a['href'].encode("utf-8")
		another_soup = BeautifulSoup(requests.get(account_url+handle).content,"html.parser")
		val = another_soup.find("a",{"data-nav":"followers"})
		value = val.contents[3].contents[0].encode("utf-8")
		print handle,value,type(value)
		if "M" in str(value):
			followers+=int(float(str(value.split("M")[0])))*1000000
			print handle,followers
		elif "K" in str(value):
			followers+=int(float(str(value.split("K")[0])))*1000
			print handle,followers
		else:
			followers+=int(str(value.replace(",","")))
			print handle,followers
	print char,":",followers
	twitter_data.write(char+","+str(followers)+"\n")
twitter_data.close()
character.close()
